import type { Metadata } from "next";
import { Lato } from "next/font/google";

import "./globals.css";

import Header from "./header";
import ScrollToTop from "./scroll-to-top";
import SmoothScroll from "./smooth-scroll";

const lato = Lato({ weight: ["400", "700", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className + " bg-white"}>
        <div id="top" className="absolute" />
        <Header />
        <SmoothScroll>{children}</SmoothScroll>
        <ScrollToTop />
      </body>
    </html>
  );
}
